### ISSUE TITLE
wasm

### ISSUE THREAD

**Issue by sphereflow** [sphereflow/light_garden#16]
Make it compile to a wasm executable

**Comment by sphereflow** [comment]
It compiles but does not run. Issues with shaders. I tried both Firefox + webgl and Firefox nightly + webgpu.
I'll wait until better support from both wgpu and Firefox.

**Comment by sphereflow** [comment]
With 8e3016b the WASM binary finally runs. Egui is not visible though.

**Comment by sphereflow** [comment]
wgpu 0.10 has moved to a full rust stack and has no ~~full WASM~~ WebGL support yet. See: #https://github.com/gfx-rs/wgpu/pull/1686

**Comment by anlumo** [comment]
wgpu should run fine in wasm with the webgpu backend, at least in my tests. For the WebGL backend you need the pull request you linked, but that's not really related to wasm itself.

**Comment by sphereflow** [comment]
Of course you are right. I was confusing terms. Do you happen to know or have any pointers on how to compile for the webgpu backend? There seems to be no related feature flag and without any feature flag I get compile errors.

**Comment by anlumo** [comment]
It picks the webgpu backend by default if you compile for wasm32. One important thing is that you have to enable [unstable APIs](https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html) in web-sys, because webgpu isn't final yet.

**Comment by sphereflow** [comment]
It compiles and runs now and egui is visible.
